jenkins:
  systemMessage: "All configuration for this controller is done as code (JCasC)"
  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: ${JENKINS_ADMIN_ID}
        password: ${JENKINS_ADMIN_PASSWORD}
        properties:
        - timezone:
            timeZoneName: "Europe/London"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
unclassified:
  location:
    url: http://jenkins.home:8080
jobs:
    - script: >
        pipelineJob("Seed or update all pipelines") {
        definition {
            cpsScm {
                scm {
                    git{
                      remote {
                        url("https://github.com/m-goos/jenkins-jobdsl-seedrepo-example.git")
                      }
                      branch("*/main")
                    }
                }
            }
          }
        }
credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          id: "DockerHub"
          password: "password"
          scope: GLOBAL
          username: "jwhitbread"
      - basicSSHUserPrivateKey:
          scope: GLOBAL
          id: jenkins-github-ssh
          username: ${GITHUB_USERNAME}
          description: "Jenkins SSH Key for github"
          privateKeySource:
            directEntry:
              privateKey: ${GITHUB_PRIV_KEY}