jenkins:
  systemMessage: "All configuration for this controller is done as code (JCasC)"
  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: ${JENKINS_ADMIN_ID}
        password: ${JENKINS_ADMIN_PASSWORD}
        properties:
        - timezone:
            timeZoneName: "Europe/London"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
unclassified:
  location:
    url: http://jenkins.home:8080
jobs:
    - script: >
        pipelineJob("Seed-Job-Or-Update-Pipelines") {
        definition {
            cpsScm {
                lightweight(true)
                scriptPath "Piplines/Seed-Job-Or-Update-Pipelines/Seed-Job-Or-Update-Pipelines.jenkinsfile"
                scm {
                    git{
                      remote {
                        credentials("jenkins-github-ssh")
                        url("https://github.com/JordanW94/jenkinsCasC.git")
                      }
                      
                      branch("refs/heads/main")
                    }
                }
            }
          }
        }
credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          id: "DockerHub"
          password: ${DOCKERHUB_PASSWORD}
          scope: GLOBAL
          username: "jwhitbread"
      - basicSSHUserPrivateKey:
          scope: GLOBAL
          id: jenkins-github-ssh
          username: ${GITHUB_USERNAME}
          description: "Jenkins SSH Key for github"
          privateKeySource:
            directEntry:
              privateKey: ${GITHUB_PRIVATE_KEY}