version: "3"
services:
  jenkinscasc:
    user: root
    container_name: jenkinscasc
    privileged: true
    image: jwhitbread/jenkinscasc:latest
    environment: # Set these accordingly
      - JENKINS_ADMIN_ID=
      - JENKINS_ADMIN_PASSWORD=
      - GITHUB_USERNAME=
      - GITHUB_PRIVATE_KEY # Set this as an environment variable: export SSH_PRIVATE_KEY=$(cat ~/.ssh/id_rsa)
      - DOCKERHUB_PASSWORD=
    restart: unless-stopped
    ports:
      - 8123:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Allows for docker to be used in docker
