version: "3"
services:
  jenkinscasc:
    user: root
    container_name: jenkinscasc
    image: jwhitbread/jenkinscasc
    restart: unless-stopped
    ports:
      - 8123:8080
    volumes:
      - ./jenkins:/var/jenkins_home/